### ISSUE TITLE
Refactoring request for Study export function

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1646]
## Description

This ticket is a technical request in order to refactor the Study export function `export_study_flat` located in the `antarest.study.storage.utils` package. The purpose of this function is to copy a Study to a destination directory with the simulation output (if this option is selected).

The current implementation needs improvement in terms of code organization and responsibility separation. I believe the following changes will enhance the overall design and maintainability of the codebase.

1. Move the export function to the `antarest.study.storage.abstract_storage_service` module:
    Currently, the export function resides in the `utils` package. To align with the code structure and improve coherence, I propose relocating the function to the `antarest.study.storage.abstract_storage_service` module.

2. Separate file copying and matrix denormalization responsibilities:
    The export function currently combines the tasks of file copying and matrix denormalization. It would be beneficial to separate these responsibilities.

3. Furthermore, I suggest implementing the denormalization directly within the two calling functions: `VariantStudyService.export_study_flat` and `RawStudyService.export_study_flat`. This approach will distribute the responsibility more effectively.

## Tasks

- [ ] refactor the code (the function can be renamed if necessary),
- [ ] add the missing documentation,
- [ ] adjust and improve unit tests regarding `export_study_flat`,
- [ ] make sure `VariantStudyService.export_study_flat` and `RawStudyService.export_study_flat` are corectly tested.
